apiVersion: batch/v1
kind: Job
metadata:
  name: otus-ma-lesson-6-db-migrations-job
spec:
  template:
    spec:
      containers:
        - name: otus-ma-lesson-6-db-migrations-job
          image: kvmayer/otus-ma-lesson-6:0.1.5
          command:
            - /app/server
            - -migrate
          env:
            - name: GRACEFUL_DELAY
              valueFrom:
                configMapKeyRef:
                  key: graceful-shutdown-sec
                  name: otus-ma-lesson-6-configmap
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: db-username
                  name: otus-ma-lesson-6-configmap
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: db-database
                  name: otus-ma-lesson-6-configmap
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: db-port
                  name: otus-ma-lesson-6-configmap
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: db-host
                  name: otus-ma-lesson-6-configmap
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-password
                  name: otus-ma-lesson-6-secret
      restartPolicy: Never
  backoffLimit: 4