apiVersion: batch/v1
kind: Job
metadata:
  name: otus-ma-lesson-6-db-migrations-job
spec:
  template:
    spec:
      containers:
        - name: otus-ma-lesson-6-db-migrations-job
          image: kvmayer/otus-ma-lesson-6:0.1.3
          command:
            - /app/server
            - -migrate
          env:
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  key: dbDsn
                  name: otus-ma-lesson-6-secret
      restartPolicy: Never
  backoffLimit: 4