apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-service.fullname" . }}
data:
  GRACEFUL_DELAY: {{ .Values.gracefulDeleay | quote }}
  DB_DATABASE: {{ .Values.postgresql.postgresqlDatabase }}
  DB_USERNAME: {{ .Values.postgresql.postgresqlUsername }}
  DB_PORT: {{ .Values.postgresql.service.port | quote }}
  DB_HOST: {{ include "postgresql.fullname" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-service.fullname" . }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
