apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-migrate" .Chart.Name }}
spec:
  template:
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:latest
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: {{ include "user-service.fullname" . }}
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: {{ include "user-service.fullname" . }}
          command:
            - sh
            - "-c"
            - |
              until pg_isready -h $POSTGRES_HOST  -p  $POSTGRES_PORT;
              do echo waiting for database; sleep 2; done;
      containers:
        - name: {{ printf "%s-migrate" .Chart.Name }}
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
          command:
            - /app/server
            - -migrate
          envFrom:
            - configMapRef:
                name: {{ include "user-service.fullname" . }}
            - secretRef:
                name: {{ include "user-service.fullname" . }}
      restartPolicy: Never
  backoffLimit: 4